### ISSUE TITLE
Update the reference for "life cycle" to remove the pointer to the IBM Style Guide

### ISSUE THREAD

**Issue by nmuller66** [StyleGuides/WritingStyleGuide#225] opened 2021-01-27 16:05 UTC
The most recent IBM Style Guide has diverged from this entry. 
This is the entry in question:
```
life cycle, life-cycle, lifecycle
    n. Two words. Only use the one-word form if it is an established part of a software interface, part of a proper noun, or an external standard.
    adj. Hyphenate.
    See The IBM Style Guide for more information. 
```
but the NEW IBM Word Usage document says:
```
lifecycle
   noun, adjective Write as shown: one word.
```
We should remove the "see the IBM style guide for more information" snippet as it provides different direction than previous IBM Style Guides and is no longer consistent with this entry.

**Comment by alexpdp7** [comment] 2021-01-27 16:08
Duplicate of https://github.com/StyleGuides/WritingStyleGuide/issues/224 ?

**Comment by daobrien** [comment] 2021-01-31 22:56
Duplicate of #224

**Closed by daobrien** 2021-01-31 22:56 UTC
